"use client";

import React from "react";
import { Document, Page, Text, View, StyleSheet, PDFDownloadLink, Font } from "@react-pdf/renderer";
import { Download } from "lucide-react";

// Register fonts
Font.register({
    family: 'Inter',
    src: 'https://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuLyfAZ9hjp-Ek-_EeA.ttf'
});

// Styles for PDF
const styles = StyleSheet.create({
    page: {
        flexDirection: "column",
        backgroundColor: "#FFFFFF",
        padding: 40,
        fontFamily: 'Inter'
    },
    header: {
        marginBottom: 20,
        borderBottom: "2px solid #EEE",
        paddingBottom: 10
    },
    title: {
        fontSize: 24,
        fontWeight: "bold",
        color: "#111827",
        marginBottom: 8
    },
    subtitle: {
        fontSize: 14,
        color: "#6B7280"
    },
    content: {
        fontSize: 12,
        lineHeight: 1.6,
        color: "#374151",
        marginBottom: 20
    },
    footer: {
        position: "absolute",
        bottom: 30,
        left: 40,
        right: 40,
        textAlign: "center",
        fontSize: 10,
        color: "#9CA3AF"
    },
    section: {
        margin: 10,
        padding: 10,
        flexGrow: 1
    }
});

// PDF Document Component
const CollateralDocument = ({ data }: { data: any }) => (
    <Document>
        <Page size="A4" style={styles.page}>
            <View style={styles.header}>
                <Text style={styles.title}>{data.title || "Untitled Document"}</Text>
                <Text style={styles.subtitle}>{data.subtitle || "Marketing Collateral"}</Text>
            </View>
            <View style={styles.section}>
                <Text style={styles.content}>
                    {data.content || "No content provided yet. Start typing to see your document take shape."}
                </Text>
            </View>
            <Text style={styles.footer}>Generated by C(AI)DENCE Marketing Suite • {new Date().getFullYear()}</Text>
        </Page>
    </Document>
);

export default function PDFDownloadButton({ data, fileName }: { data: any, fileName: string }) {
    return (
        <PDFDownloadLink
            document={<CollateralDocument data={data} />}
            fileName={fileName}
        >
            {/* @ts-ignore */}
            {({ blob, url, loading, error }) => (
                <button
                    disabled={loading}
                    className="flex items-center gap-2 px-4 py-2 bg-white text-slate-900 font-bold rounded-lg hover:bg-slate-100 transition-colors disabled:opacity-50"
                >
                    {loading ? "Generating..." : (
                        <>
                            <Download className="w-4 h-4" />
                            Download PDF
                        </>
                    )}
                </button>
            )}
        </PDFDownloadLink>
    );
}
