"use client";

import React from "react";
import { Document, Page, Text, View, StyleSheet, PDFDownloadLink, Font } from "@react-pdf/renderer";
import { Download } from "lucide-react";

// Register fonts
Font.register({
    family: 'Inter',
    src: 'https://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuLyfAZ9hjp-Ek-_EeA.ttf'
});

// Styles for PDF
const styles = StyleSheet.create({
    page: {
        flexDirection: "column",
        backgroundColor: "#FFFFFF",
        padding: 40,
        fontFamily: 'Inter'
    },
    header: {
        marginBottom: 20,
        borderBottom: "2px solid #EEE",
        paddingBottom: 10
    },
    title: {
        fontSize: 24,
        fontWeight: "bold",
        color: "#111827",
        marginBottom: 8
    },
    slideNumber: {
        position: "absolute",
        top: 40,
        right: 40,
        fontSize: 10,
        color: "#9CA3AF"
    },
    content: {
        fontSize: 14,
        lineHeight: 1.6,
        color: "#374151",
        marginBottom: 20
    },
    footer: {
        position: "absolute",
        bottom: 30,
        left: 40,
        right: 40,
        textAlign: "center",
        fontSize: 10,
        color: "#9CA3AF"
    },
    coverPage: {
        flexDirection: "column",
        backgroundColor: "#FFFFFF",
        padding: 40,
        fontFamily: 'Inter',
        justifyContent: "center",
        alignItems: "center"
    },
    coverTitle: {
        fontSize: 32,
        fontWeight: "bold",
        color: "#111827",
        marginBottom: 16,
        textAlign: "center"
    },
    coverSubtitle: {
        fontSize: 16,
        color: "#6B7280",
        textAlign: "center"
    }
});

interface Slide {
    title: string;
    content: string;
}

interface PresentationData {
    title: string;
    created_at: string;
    slides: Slide[];
}

// PDF Document Component
const PresentationDocument = ({ data }: { data: PresentationData }) => (
    <Document>
        {/* Cover Page */}
        <Page size="A4" style={styles.coverPage}>
            <Text style={styles.coverTitle}>{data.title}</Text>
            <Text style={styles.coverSubtitle}>Generated by C(AI)DENCE</Text>
            <Text style={[styles.coverSubtitle, { marginTop: 20, fontSize: 12 }]}>
                {new Date(data.created_at).toLocaleDateString()}
            </Text>
        </Page>

        {/* Slides */}
        {data.slides.map((slide, index) => (
            <Page key={index} size="A4" style={styles.page}>
                <Text style={styles.slideNumber}>Slide {index + 1}</Text>
                <View style={styles.header}>
                    <Text style={styles.title}>{slide.title}</Text>
                </View>
                <View>
                    <Text style={styles.content}>
                        {slide.content}
                    </Text>
                </View>
                <Text style={styles.footer}>C(AI)DENCE Presentation Studio</Text>
            </Page>
        ))}
    </Document>
);

export default function PresentationPDFDownload({ data, fileName }: { data: PresentationData, fileName: string }) {
    return (
        <PDFDownloadLink
            document={<PresentationDocument data={data} />}
            fileName={fileName}
        >
            {/* @ts-ignore */}
            {({ blob, url, loading, error }) => (
                <button
                    disabled={loading}
                    className="flex items-center gap-2 px-4 py-2 border bg-white border-slate-200 text-slate-600 rounded-xl text-sm font-bold shadow-sm hover:bg-slate-50 transition-all disabled:opacity-50"
                >
                    {loading ? "Preparing..." : (
                        <>
                            <Download className="w-4 h-4" />
                            Export PDF
                        </>
                    )}
                </button>
            )}
        </PDFDownloadLink>
    );
}
