"""Add CreditAccount and CreditTransaction models for credit tracking

Revision ID: ba4b43132dd1
Revises: 7d4f0252b522
Create Date: 2026-02-05 16:25:56.169416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba4b43132dd1'
down_revision: Union[str, Sequence[str], None] = '7d4f0252b522'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creator_searches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('query', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('filters', sa.Text(), nullable=True),
    sa.Column('result_count', sa.Integer(), nullable=True),
    sa.Column('credits_used', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('creator_searches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_creator_searches_id'), ['id'], unique=False)

    op.create_table('credit_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('monthly_allotment', sa.Float(), nullable=True),
    sa.Column('total_spent', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reset_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('credit_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credit_accounts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_accounts_user_id'), ['user_id'], unique=True)

    op.create_table('credit_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('credit_account_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('balance_before', sa.Float(), nullable=True),
    sa.Column('balance_after', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('api_call_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['credit_account_id'], ['credit_accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('credit_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credit_transactions_credit_account_id'), ['credit_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_transactions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_transactions_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('creators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_blacklisted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('design_assets', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('design_assets', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    with op.batch_alter_table('creators', schema=None) as batch_op:
        batch_op.drop_column('is_blacklisted')
        batch_op.drop_column('is_verified')

    with op.batch_alter_table('credit_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credit_transactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_credit_transactions_id'))
        batch_op.drop_index(batch_op.f('ix_credit_transactions_credit_account_id'))

    op.drop_table('credit_transactions')
    with op.batch_alter_table('credit_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credit_accounts_user_id'))
        batch_op.drop_index(batch_op.f('ix_credit_accounts_id'))

    op.drop_table('credit_accounts')
    with op.batch_alter_table('creator_searches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creator_searches_id'))

    op.drop_table('creator_searches')
    # ### end Alembic commands ###
